package testy;

import java.util.List;
import java.util.ArrayList;

public class main {

	public static void main(String[] args) {
		
		List<karta> talia = stworzTalie();
		List<gracz> gracze = new ArrayList<gracz>();
		List<postac> postacie = listaPostaci();
		gracz tmp;
		tmp=new gracz("wardasz");
		gracze.add(tmp);
		tmp=new gracz("arame");
		gracze.add(tmp);
		tmp=new gracz("asirra");
		gracze.add(tmp);
		tmp=new gracz("lowca");
		gracze.add(tmp);
		tmp=new gracz("rin");
		gracze.add(tmp);
		
		gra Gra = new gra(gracze, talia);
		//Gra.graj();
		Gra.zassaj();
		Gra.napiszGraczy();
		karta k = new sklep(53, "Indianie", 13, "karo");
		System.out.print("\nZagrywam sklep\n");
		k.zagraj();
		Gra.napiszGraczy();
		//Gra.napiszCmentaz();

	}
	
	public static List<karta> stworzTalie() {
		List<karta> talia = new ArrayList<karta>();
		karta tmp;
				
		tmp = new eq(1, "Volcanic", 10, "pik", true, 1, 0, false, true);
		talia.add(tmp);
		tmp = new eq(2, "Volcanic", 10, "trefl", true, 1, 0, false, true);
		talia.add(tmp);
		tmp = new eq(3, "Schofield", 13, "pik", true, 2, 0, false, false);
		talia.add(tmp);
		tmp = new eq(4, "Schofield", 11, "trefl", true, 2, 0, false, false);
		talia.add(tmp);
		tmp = new eq(5, "Schofield", 12, "trefl", true, 2, 0, false, false);
		talia.add(tmp);
		tmp = new eq(6, "Remington", 13, "trefl", true, 3, 0, false, false);
		talia.add(tmp);
		tmp = new eq(7, "Rev Carabine", 14, "trefl", true, 4, 0, false, false);
		talia.add(tmp);
		tmp = new eq(8, "Winchester", 8, "pik", true, 5, 0, false, false);
		talia.add(tmp);
		tmp = new eq(9, "Luneta", 14, "pik", false, 1, 0, false, false);
		talia.add(tmp);
		tmp = new eq(10, "Bary趾a", 14, "pik", false, 0, 0, true, false);
		talia.add(tmp);
		tmp = new eq(11, "Bary趾a", 12, "pik", false, 0, 0, true, false);
		talia.add(tmp);
		tmp = new eq(12, "Mustang", 8, "kier", false, 0, 1, false, false);
		talia.add(tmp);
		tmp = new eq(13, "Mustang", 9, "kier", false, 0, 1, false, false);
		talia.add(tmp);
		tmp = new piwko(14, "Piwko", 6, "kier");
		talia.add(tmp);
		tmp = new piwko(15, "Piwko", 7, "kier");
		talia.add(tmp);
		tmp = new piwko(16, "Piwko", 8, "kier");
		talia.add(tmp);
		tmp = new piwko(17, "Piwko", 9, "kier");
		talia.add(tmp);
		tmp = new piwko(18, "Piwko", 10, "kier");
		talia.add(tmp);
		tmp = new piwko(19, "Piwko", 11, "kier");
		talia.add(tmp);
		tmp = new dynamit(20, "Dynamit", 2, "kier");
		talia.add(tmp);
		tmp = new bang(21, "Bang", 12, "kier");
		talia.add(tmp);
		tmp = new bang(22, "Bang", 13, "kier");
		talia.add(tmp);
		tmp = new bang(23, "Bang", 14, "kier");
		talia.add(tmp);
		tmp = new bang(24, "Bang", 2, "karo");
		talia.add(tmp);
		tmp = new bang(25, "Bang", 3, "karo");
		talia.add(tmp);
		tmp = new bang(26, "Bang", 4, "karo");
		talia.add(tmp);
		tmp = new bang(27, "Bang", 5, "karo");
		talia.add(tmp);
		tmp = new bang(28, "Bang", 6, "karo");
		talia.add(tmp);
		tmp = new bang(29, "Bang", 7, "karo");
		talia.add(tmp);
		tmp = new bang(30, "Bang", 8, "karo");
		talia.add(tmp);
		tmp = new bang(31, "Bang", 9, "karo");
		talia.add(tmp);
		tmp = new bang(32, "Bang", 10, "karo");
		talia.add(tmp);
		tmp = new bang(33, "Bang", 11, "karo");
		talia.add(tmp);
		tmp = new bang(34, "Bang", 12, "karo");
		talia.add(tmp);
		tmp = new bang(35, "Bang", 13, "karo");
		talia.add(tmp);
		tmp = new bang(36, "Bang", 14, "karo");
		talia.add(tmp);
		tmp = new bang(37, "Bang", 14, "pik");
		talia.add(tmp);
		tmp = new bang(38, "Bang", 2, "trefl");
		talia.add(tmp);
		tmp = new bang(39, "Bang", 3, "trefl");
		talia.add(tmp);
		tmp = new bang(40, "Bang", 4, "trefl");
		talia.add(tmp);
		tmp = new bang(41, "Bang", 5, "trefl");
		talia.add(tmp);
		tmp = new bang(42, "Bang", 6, "trefl");
		talia.add(tmp);
		tmp = new bang(43, "Bang", 7, "trefl");
		talia.add(tmp);
		tmp = new bang(44, "Bang", 8, "trefl");
		talia.add(tmp);
		tmp = new bang(45, "Bang", 9, "trefl");
		talia.add(tmp);
		tmp = new welsfargo(46, "Wells Fargo", 3, "kier");
		talia.add(tmp);
		tmp = new dylizans(47, "Dyli瘸ns", 9, "pik");
		talia.add(tmp);
		tmp = new dylizans(48, "Dyli瘸ns", 9, "pik");
		talia.add(tmp);
		tmp = new wiezienie(49, "Wi瞛ienie", 4, "kier");
		talia.add(tmp);
		tmp = new wiezienie(50, "Wi瞛ienie", 11, "pik");
		talia.add(tmp);
		tmp = new wiezienie(51, "Wi瞛ienie", 10, "pik");
		talia.add(tmp);
		tmp = new salon(52, "Saloon", 5, "kier");
		talia.add(tmp);
		tmp = new gatling(53, "Gatling", 10, "kier");
		talia.add(tmp);
		tmp = new pudlo(54, "Pud這", 2, "pik");
		talia.add(tmp);
		tmp = new pudlo(55, "Pud這", 3, "pik");
		talia.add(tmp);
		tmp = new pudlo(56, "Pud這", 4, "pik");
		talia.add(tmp);
		tmp = new pudlo(57, "Pud這", 5, "pik");
		talia.add(tmp);
		tmp = new pudlo(58, "Pud這", 6, "pik");
		talia.add(tmp);
		tmp = new pudlo(59, "Pud這", 7, "pik");
		talia.add(tmp);
		tmp = new pudlo(60, "Pud這", 8, "pik");
		talia.add(tmp);
		tmp = new pudlo(61, "Pud這", 10, "trefl");
		talia.add(tmp);
		tmp = new pudlo(62, "Pud這", 11, "trefl");
		talia.add(tmp);
		tmp = new pudlo(63, "Pud這", 12, "trefl");
		talia.add(tmp);
		tmp = new pudlo(64, "Pud這", 13, "trefl");
		talia.add(tmp);
		tmp = new pudlo(65, "Pud這", 14, "trefl");
		talia.add(tmp);
		tmp = new kasia(66, "Kasia Balou", 13, "kier");
		talia.add(tmp);
		tmp = new kasia(67, "Kasia Balou", 9, "karo");
		talia.add(tmp);
		tmp = new kasia(68, "Kasia Balou", 10, "karo");
		talia.add(tmp);
		tmp = new kasia(69, "Kasia Balou", 11, "karo");
		talia.add(tmp);
		tmp = new panika(70, "Panika", 8, "karo");
		talia.add(tmp);
		tmp = new panika(71, "Panika", 11, "kier");
		talia.add(tmp);
		tmp = new panika(72, "Panika", 12, "kier");
		talia.add(tmp);	
		tmp = new panika(73, "Panika", 14, "kier");
		talia.add(tmp);
		tmp = new sklep(74, "Sklep", 12, "pik");
		talia.add(tmp);	
		tmp = new sklep(75, "Sklep", 9, "trefl");
		talia.add(tmp);
		tmp = new pojedynek(76, "Pojedynek", 12, "karo");
		talia.add(tmp);
		tmp = new pojedynek(77, "Pojedynek", 11, "pik");
		talia.add(tmp);	
		tmp = new pojedynek(78, "Pojedynek", 8, "trefl");
		talia.add(tmp);
		tmp = new indianie(79, "Indianie", 13, "karo");
		talia.add(tmp);
		tmp = new indianie(80, "Indianie", 14, "karo");
		talia.add(tmp);
		
		return talia;
	}
	
	public static List<postac> listaPostaci(){
		List<postac> lista = new ArrayList<postac>();
		postac tmp;
		
		tmp = new postac(1, 4, "Bart Cassady");
		lista.add(tmp);
		tmp = new postac(2, 4, "Black Jack");
		lista.add(tmp);
		tmp = new postac(3, 4, "Calamity Janet");
		lista.add(tmp);
		tmp = new postac(4, 3, "El Gringo");
		lista.add(tmp);
		tmp = new postac(5, 4, "Jesse Jones");
		lista.add(tmp);
		tmp = new postac(6, 4, "Jourdonnais");
		lista.add(tmp);
		tmp = new postac(7, 4, "Kit Carlson");
		lista.add(tmp);
		tmp = new postac(8, 4, "Lusky Duke");
		lista.add(tmp);
		tmp = new postac(9, 3, "Paul Regret");
		lista.add(tmp);
		tmp = new postac(10, 4, "Pedro Ramizer");
		lista.add(tmp);
		tmp = new postac(11, 4, "Rose Doolan");
		lista.add(tmp);
		tmp = new postac(12, 4, "Sid Ketchum");
		lista.add(tmp);
		tmp = new postac(13, 4, "Slab Zab鎩ca");
		lista.add(tmp);
		tmp = new postac(14, 4, "Suzy Lafayette");
		lista.add(tmp);
		tmp = new postac(15, 4, "Sam S瘼");
		lista.add(tmp);
		tmp = new postac(16, 4, "Willy the Kid");
		lista.add(tmp);	
		
		return lista;
	}
}
